### ISSUE TITLE
Missing versioning for 1.1.0 and 1.1.1 releases

### ISSUE THREAD

**Issue by bdrelling** [ggerganov/whisper.spm#2]
Hello @ggerganov!

I noticed that there are updates coming into this repo from the `whisper.cpp` repo, for `1.1.0` and `1.1.1` specifically, but no associated tag created. Do you plan to add tags alongside releases? We're currently commit-locked but we'd love to use versioning instead.

Thanks!

**Comment by ggerganov** [comment]
Oops, I forgot to push the tags!
Yes - the plan is to tag the new releases in this repo too.

**Comment by bdrelling** [comment]
Thank you so much!
