### ISSUE TITLE
More frequent integration of whisper.cpp commits?

### ISSUE THREAD

**Issue by bdrelling** [ggerganov/whisper.spm#7]
Is it possible to get more frequent integration of `whisper.cpp` commits?

Currently, `whisper.spm` only seems to be receiving versioned updates from `whisper.cpp`, but `whisper.cpp` frequently gets commits that would benefit us immediately, and it can take a while before they are brought over to `whisper.spm`. 

We are also commit-locked to `whisper.spm`, not version-locked (because of the [unsafe build flags](https://github.com/ggerganov/whisper.spm/issues/4) issue), so there'd be little problem from our perspective with updating to specified commits or using a "bleeding edge" version of `whisper.cpp`.

Thanks!

**Comment by ggerganov** [comment]
Sure, no problem. I might setup some CI to auto-sync this repo with `whisper.cpp`

**Comment by mortenjust** [comment]
This would be amazing. I'm also really excited to try the coreml version with SPM and seeing it in a polished UI like this


<img width="500" alt="CleanShot 2023-03-08 at 17 56 32@2x" src="https://user-images.githubusercontent.com/1548468/223778366-8781dbe0-53e7-4ce9-8179-d259b9dffdfa.png">

**Comment by ggerganov** [comment]
[v1.3.0](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.3.0) has Core ML support
