### ISSUE TITLE
CoreML support for Whisper.spm

### ISSUE THREAD

**Issue by venkr** [ggerganov/whisper.spm#9]
Any idea how we could get CoreML support via Whisper.spm.

I've tried passing in `-DWHISPER_COREML=1` - but it doesn't seem to work for me. Any ideas?

I'm wiling to help work on this if anyone has any specific ideas for how we could approach this.

**Comment by sbychin** [comment]
I'm interested in this as well so if I have any ideas or solutions I'll post it here.

Hey @ggerganov, were you able to find any solution on how to implement CoreML support?

Thanks in advance!

**Comment by ggerganov** [comment]
Sorry for the delay - is this still relevant after the change in #13

**Comment by venkr** [comment]
> Sorry for the delay - is this still relevant after the change in #13

Closed by #13
